# Generated by Django 3.1 on 2022-03-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cus',
            name='email',
        ),
    ]
