# Generated by Django 3.1 on 2022-03-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_cus_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cus',
            old_name='password_hash',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='cus',
            name='password_salt',
        ),
    ]
