# Generated by Django 3.1 on 2022-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220329_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='cus',
            name='email',
            field=models.EmailField(default='abc', max_length=254),
        ),
    ]
