# Generated by Django 3.1 on 2022-03-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_cus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
