# Generated by Django 3.1 on 2022-03-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_salt',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='123@123.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNo',
            field=models.CharField(default='123', max_length=10),
        ),
    ]
